SELECT
    bill.fid as "id",
    bill.FPROCDEFID as "流程定义ID",
    bill.FPROCINSTID as "流程实例ID",
    bill.FBUSINESSKEY as "业务主键",
    bill.FPARENTID as "父流程实例ID",
    bill.FSUPEREXEC as "主流程实例ID",
    bill.fbusinessid as "流程标识",
    bill.FROOTPROCINSTID as "根流程实例ID",
    bill.FACTID as "当前活动节点ID",
    bill.FTASKID as "当前任务ID",
    bill.FACTINSTID as "当前节点实例ID",
    bill.FISACTIVE as "是否存活",
    bill.FISCONCURRENT as "是否单据实例",
    bill.FISSCOPE as "作用范围",
    bill.FISEVENTSCOPE as "事件范围",
    bill.FISMIROOT as "是否多实例根",
    start_user.fnumber as "发起人工号",
    start_user.ftruename as "发起人姓名",
    bill.FLOCKTIME as "锁定时间",
    bill.FISCOUNTENABLED as "是否计数",
    bill.FEVTSUBSCRCOUNT as "事件子脚本数",
    bill.FTASKCOUNT as "任务数",
    bill.FJOBCOUNT as "工作数",
    bill.FTIMERJOBCOUNT as "定时工作数",
    bill.FSUSPJOBCOUNT as "挂起工作数",
    bill.FDEADLETTERJOBCOUNT as "死信工作数",
    bill.FVARCOUNT as "变量数",
    bill.FIDLINKCOUNT as "用户连接数",
    bill.fbillno as "单据编码",
    bill.fentitynumber as "单据类型",
    bill.FNAME as "名称",
    bill.FDESCRIPTION as "描述",
    bill.FSUSPENSIONSTATE as "流程状态",
    bill.fcreatedate as "创建日期",
    bill.fmodifydate as "修改时间",
    bill.fentrabillname as "入口单据名称",
    bill.fsubject as "单据主题",
    bill.factivityname as "当前节点",
    _org.FNAME as "组织名称",
    bill.forgviewid as "组织类型",
    bill.fschemeid as "方案id",
    bill.ftestingplanid as "测试计划id",
    create_user.fnumber as "创建人工号",
    create_user.ftruename as "创建人姓名",
    modeify_user.fnumber as "修改人工号",
    modeify_user.ftruename as "修改人姓名",
    bill.fbilltype as "业务单据类型",
    bill.fbiztraceno as "业务跟踪号",
    bill.fbatchnumber as "批次号",
    bill.fprocesstype as "流程类型",
    bill.fstarusernameformat as "发起人姓名格式化",
    bill.fpresentassignee as "当前处理人",
    bill.fcachedentstate as "终止类型",
    bill.fpriorityshow as "标记显示"
FROM
    crrc_wfs.T_WF_EXECUTION bill
    LEFT JOIN crrc_sys.t_sec_user start_user ON bill.FSTARTUSERID = start_user.fid
    LEFT JOIN crrc_sys.t_org_org _org ON bill.fmainorgid = _org.fid
    LEFT JOIN crrc_sys.t_sec_user create_user ON bill.fcreatorid = create_user.fid
    LEFT JOIN crrc_sys.t_sec_user modeify_user ON bill.fmodifierid = modeify_user.fid