SELECT
    id,
    "applicationNumber" AS "单据编号",
    "name" AS "申请人姓名",
    "idNumber" AS "身份证号",
    "companyName" AS "公司名称",
    "phoneNumber" AS "联系电话",
    "submitTime" AS "提交时间",
    "startDate" AS "计划开工日期",
    "startTime" AS "计划开工时间",
    "workingHours" AS "计划工作时长",
    "workLocation" AS "工作地点",
    "workType" AS "作业类型",
    "isProductWork" AS "是否为产品类作业",
    "projectName" AS "项目名称",
    "vehicleNumber" AS "车号",
    "trackPosition" AS "车道",
    "workContent" AS "具体作业内容",
    "workBasis" AS "作业依据",
    "basisNumber" AS "NCR/开口项/设计变更编号",
    "dangerTypes" AS "危险源类型",
    "notifierName" AS "事业部对接人名称",
    "notifierNumber" AS "事业部对接人工号",
    "notifierDepartment" AS "事业部对接人所属部门",
    "accompaningCount" AS "随行人员数量"
FROM safeformhead