# 连接配置文件

["外网访客系统数据库"]
# 注意，该数据库仅能在10.24.5.54访问得到
type = "mongo"
ip = "18.0.163.64"
port = 10086
user = ""
password = ""
write_enable = true

["BI与数开用数据库"]
type = "mysql"
ip = "10.24.5.32"
port = 3306
user = "cheakf"
password = "Swq8855830."
database = "dataframe_flow_v2"
write_enable = true

["BI与数开用数据库_旧"]
type = "mysql"
ip = "10.24.5.32"
port = 3306
user = "cheakf"
password = "Swq8855830."
database = "dataframe_flow"
write_enable = true

["BI与数开用数据库_供应商"]
type = "mysql"
ip = "10.24.5.32"
port = 3306
user = "cheakf"
password = "Swq8855830."
database = "supplier_use"
write_enable = true

[EAS]
type = "oracle"
ip = "172.18.1.121"
port = 1521
user = "easselect"
password = "easselect"
database = "eas"
write_enable = false

[MES]
type = "oracle"
ip = "10.24.212.17"
port = 1521
user = "unimax_cg"
password = "unimax_cg"
database = "ORCL"
write_enable = false

[SHR]
type = "oracle"
ip = "10.24.204.67"
port = 1521
user = "shr_query"
password = "shr_queryZj123!"
database = "ORCL"
write_enable = false

["生产辅助系统"]
type = "sqlserver"
ip = "10.24.5.154"
port = 1433
user = "metro"
password = "Metro2023!"
database = "城轨事业部"
write_enable = false

["生产辅助系统-中转"]
type = "sqlserver"
ip = "10.24.5.154"
port = 1433
user = "metro"
password = "Metro2023!"
database = "crrc_temp"
write_enable = true

["金蝶云苍穹-测试库"]
type = "mysql"
ip ="10.24.204.37"
port = 3306
user = "kingdee"
password = "kingdee2020"
database = "crrc_phm"
write_enable = false

["金蝶云苍穹-正式库"]
type = "mysql"
ip = "10.24.206.138"
port = 3306
user = "cosmic"
password = "Mysql@2022!"
database = "crrc_secd"
write_enable = false

["金蝶云苍穹-正式库-系统"]
type = "mysql"
ip = "10.24.206.138"
port = 3306
user = "cosmic"
password = "Mysql@2022!"
database = "crrc_sys"
write_enable = false

["机车数据库"]
type = "mysql"
ip = "10.29.31.159"
port = 3306
user = "crrc_temp"
password = "ETxkrRpCFDZ4LmMr"
database = "crrc_temp"
write_enable = true

["智能立库"]
type = "mysql"
ip = "10.24.5.21"
port = 3307
user = "root"
password = "jftxAdmin"
database = "smart_warehouse"
write_enable = false

["考勤系统"]
type = "sqlserver"
ip = "10.24.7.48"
port = 1433
user = "sa"
password = "Z@hc#8705!$"
database = "GM_MT_70"
write_enable = false

["数据运用平台-测试库"]
type = "mysql"
ip = "10.24.7.145"
port = 3316
user = "zjuser"
password = "zjuser@123"
database = "zj_data"
write_enable = true

["数据运用平台-正式库"]
type = "mysql"
ip = "10.24.207.80"
port = 8082
user = "root"
password = "WnXPLOS8ch"
database = "zj_data"
write_enable = false

