# 连接配置文件

["mongo测试"]
# 注意，该数据库仅能在10.24.5.54访问得到
type = "mongo"
ip = "localhost"
port = 27017
user = ""
password = ""
write_enable = true

["mysql测试"]
type = "mysql"
ip = "localhost"
port = 3306
user = "root"
password = "Swq8855830."
database = "mysql"
write_enable = true

["oracle测试"]
type = "oracle"
ip = "localhost"
port = 1521
user = "system"
password = "Swq8855830."
database = "ORCL"
write_enable = true

["sqlserver测试"]
type = "sqlserver"
ip = "localhost"
port = 1433
user = "sa"
password = "Swq8855830."
database = "master"
write_enable = true

